### PR TITLE
Merge next-release branch for 2.1.0 release

### PR DESCRIPTION
**Pull request by ctubbsii**
This PR incorporates the changes staged in the `next-release` branch into the `main` branch, and should be merged only *after* the next release (2.1.0). In the interim, additional changes intended to be delayed until after the 2.1.0 release should be submitted against the `next-release` branch. Changes that are safe to be merged into the `main` branch should continue to be submitted there (such as changes to the draft release notes). This PR may be updated as this branch is rebased periodically and kept up-to-date with the `main` branch.

### CODE REVIEW

**Comment by milleruntime** [comment]
This is a great idea. Thanks @ctubbsii 

Should we include release notes? I guess those can still be merged ahead of time thanks to the 'draft' tag.

**Comment by ctubbsii** [comment]
> Should we include release notes?

Nah.

> I guess those can still be merged ahead of time thanks to the 'draft' tag.

Yup.

**Comment by EdColeman** [comment]
Is this really ready to merge? I thought we'd wait for the release to occur.

**Review by EdColeman — APPROVED** [review]

**Comment by ctubbsii** [comment]
This won't get merged until after the release.

**Pull request merged**
