### PR TITLE
ACCUMULO-4480 Update 1.8 user manual

### PR DESCRIPTION
**Pull request by mjwall**
@ctubbsii let me know if that is better

### CODE REVIEW

**Comment by mjwall** [comment]
@mikewalch are you saying that I need to also put these changes into the gh-pages and asf-site branch of the https://github.com/apache/accumulo?  Which repo are we using to push changes to the live site?

**Comment by mikewalch** [comment]
@mjwall, Sorry, I don't think I was clear enough.  Did you makes these changes to the manual asciidoc in for 1.8 branch and master branch of apache/accumulo repo?  If we do another 1.8.* release, these changes will be lost if they are not included in the 1.8 branch.

**Comment by mjwall** [comment]
Oh, no I did not.  I am trying to do a 1.8.1 though.  So user manual changes should made to the asciidoc under accumulo-docs, which will then gets generated and put into the accumulo-website repo?  Thanks, I guess I don't fully understand the process yet.

**Comment by mikewalch** [comment]
Yes, when you change the user manual, you should change it in asciidoc under accumulo/docs, generate it again, and copy the the manual html to the website repo.

**Comment by mjwall** [comment]
Gotcha, thanks for keeping me inline.

**Comment by mjwall** [comment]
Closing this PR, will make a PR on accumulo for this and copy over when merged

**Comment by mikewalch** [comment]
Also, if you want the changes up immediately on the website then you can copy them over to website repo when merged.  If they are minor, you can put them into the 1.8 branch and just wait for the next 1.8 release (assuming they are generated and copied for each bugfix release).

**Pull request closed without merging**
