### PR TITLE
Add prominent link to public API docs

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Review by dlmarion — APPROVED** [review]

**Comment by keith-turner** [comment]
I thought there used to be a prominent link to this, however I can not find it if there is.

**Comment by milleruntime** [comment]
Closes https://github.com/apache/accumulo-website/issues/207

**Comment by milleruntime** [comment]
There is also a link on the main page under "Stable" feature to "client api" which we may want to change to this as well.

**Comment by keith-turner** [comment]
> There is also a link on the main page under "Stable" feature to "client api" which we may want to change to this as well.

That seems to link to Javadoc that only includes the public API.  If so maybe the /api page should link to this javadoc and then "client api" link under "Stable" could link to /api

**Pull request merged**
