### PR TITLE
Add necessary imports and removed unused exception

### PR DESCRIPTION
**Pull request by rcarterjr**
I ran into importing issues when going through the tour, so I added what was needed and removed an unused exception.

### CODE REVIEW

**Comment by milleruntime** [comment]
Hey @rcarterjr thanks for the contribution!  The tour is a little out of date but I was planning on updating it soon.  I was just curious, what version of Accumulo and Java were you running?  And which steps on the tour did you run into issues?

**Comment by rcarterjr** [comment]
I'm running Accumulo 2.0.0 with Java 8. The first 4 of 11 steps ran properly, but every step after that needed multiple imports.

**Comment by milleruntime** [comment]
> I'm running Accumulo 2.0.0 with Java 8. The first 4 of 11 steps ran properly, but every step after that needed multiple imports.

2.0.0-alpha-2 ?

**Comment by rcarterjr** [comment]
2.0.0-SNAPSHOT from GitHub

**Comment by milleruntime** [comment]
OK cool. I will go ahead and merge your updates.  If you want to be added to our list of contributors please feel free to open a PR up against the website here: https://accumulo.apache.org/people/
Thanks!

**Pull request merged**
