### PR TITLE
revise grammar

### PR DESCRIPTION
**Pull request by rcarterjr**
I came across a minor grammar error while reading the docs.

### CODE REVIEW

**Comment by ctubbsii** [comment]
For future reference, "data are" is grammatically correct, even though it doesn't seem like it: https://blog.apastyle.org/apastyle/2012/07/data-is-or-data-are.html
("data" is plural, "datum" is singular)

However, in this case, the incorrect form is more familiar, and it probably doesn't matter much.

**Comment by AdamAce38** [comment]
https://repo1.maven.org/maven2/com/google/

**Comment by AdamAce38** [comment]
https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8814/3/

**Comment by AdamAce38** [comment]
distfiles.m❔❔❔ort❔.org   1PASSWORD

**Comment by AdamAce38** [comment]
https://distfiles.macports.org

**Pull request merged**
