### PR TITLE
Update contributors list to add Amisha Sahu

### PR DESCRIPTION
**Pull request by Amisha328**
Fixed issue #2066 with PR #2071 - made map final in MapCounter.java

### CODE REVIEW

**Review by EdColeman — APPROVED** [review]

**Comment by Amisha328** [comment]
Hey, @EdColeman 
I wanted to ask that I could see my name in the contributes list in people.md but I can't find it on the website : [https://accumulo.apache.org/people/](https://accumulo.apache.org/people/).

May I know why?

**Comment by EdColeman** [comment]
Currently it is visible in the [staging site](https://accumulo.staged.apache.org/people/) - when that gets pushed to update the main site, it will appear.  There is nothing you need to do.

**Comment by Amisha328** [comment]
Thanks a lot for confirming!

**Comment by EdColeman** [comment]
@Amisha328 - the changes have been pushed to the main site and your name is shown at the [main site](https://accumulo.apache.org/people/). Thanks for your contribution.

**Comment by Amisha328** [comment]
Thanks a lot @EdColeman

**Pull request merged**
