### PR TITLE
Add new blog post for 2.1.0 metrics and tracing changes

### PR DESCRIPTION
**Pull request by dlmarion**

### CODE REVIEW

**Comment by EdColeman** [comment]
Would it be better to target next-release?  Although with a blog post, maybe just indicate new with 2.1 and if someone wants, they can just pull from main and try it?  Not really an answer, because I'm fuzzy on the protocol for this.  I guess one issue with publishing it now (on main) would be if anything changed before the 2.1 release that would need and update.

**Comment by dlmarion** [comment]
I targeted `main` because the [External Compactions](https://accumulo.apache.org/blog/2021/07/08/external-compactions.html) blog is already there. It's like a preview of what's to come. It looks like there might be a GitHub [action](https://github.com/apache/accumulo-website/blob/main/.github/workflows/jekyll.yaml) that deploys the site when a push is made to `main` or `next-release`. I'm not quite sure where the `next-release` branch is located though.

**Comment by dlmarion** [comment]
Based on [this](https://github.com/apache/accumulo-website#publishing) it looks like when I merge this it will be available at https://accumulo.staged.apache.org/. We can review it before updating the main site using the instructions in the README.

**Comment by dlmarion** [comment]
Blog post available for review at https://accumulo.staged.apache.org/blog/2022/06/22/2.1.0-metrics-and-tracing.html

**Comment by dlmarion** [comment]
I reviewed the staged blog content and checked all links. LGTM.

**Comment by dlmarion** [comment]
Any issues if I push the staged website out to `apache.accumulo.org` ?

**Comment by dlmarion** [comment]
blog published to asf-site.

**Pull request merged**
